language: php
php:
  - 5.2
  - 5.3
  - 5.4
before_script:
  - wget http://downloads.sourceforge.net/project/simpletest/simpletest/simpletest_1.1/simpletest_1.1.0.tar.gz
  - tar -xvzf simpletest_1.1.0.tar.gz
  - pear install PHP_CodeSniffer
  - phpenv rehash
script: 
  - phpcs src --standard=./phpcs_ruleset.xml
  - php test/run-tests.php
